# Generated by Django 5.0.2 on 2024-02-26 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 18, 14, 2, 196725, tzinfo=datetime.timezone.utc)),
        ),
    ]
